import { ProjectSummary, CocomoResult } from "./types";

export const mockProjectSummary: ProjectSummary = {
  path: "D:/Code/Locsight",
  totalFiles: 42,
  totalLanguages: 6,
  totalCode: 12450,
  totalComments: 1820,
  totalBlanks: 1680,
  totalLoc: 15950,
  languages: [
    { name: "Rust", files: 16, code: 6200, comments: 920, blanks: 860, pct: 49.8 },
    { name: "TypeScript", files: 14, code: 4150, comments: 510, blanks: 520, pct: 33.3 },
    { name: "TOML", files: 3, code: 1420, comments: 230, blanks: 190, pct: 11.4 },
    { name: "CSS", files: 5, code: 430, comments: 80, blanks: 60, pct: 3.5 },
    { name: "JSON", files: 3, code: 190, comments: 10, blanks: 30, pct: 1.5 },
    { name: "Markdown", files: 1, code: 60, comments: 70, blanks: 20, pct: 0.5 },
  ],
  files: [
    { name: "scanner.rs", path: "src-tauri/src/engine/scanner.rs", lang: "Rust", loc: 860, code: 710, comments: 90, blanks: 60, sizeBytes: 29400, complexity: 14.2 },
    { name: "techstack.rs", path: "src-tauri/src/engine/techstack.rs", lang: "Rust", loc: 474, code: 390, comments: 44, blanks: 40, sizeBytes: 19414, complexity: 8.5 },
    { name: "architecture.rs", path: "src-tauri/src/engine/architecture.rs", lang: "Rust", loc: 350, code: 280, comments: 38, blanks: 32, sizeBytes: 11115, complexity: 7.1 },
    { name: "assets.rs", path: "src-tauri/src/engine/assets.rs", lang: "Rust", loc: 345, code: 275, comments: 35, blanks: 35, sizeBytes: 12100, complexity: 6.8 },
    { name: "Graph.tsx", path: "src/components/Graph.tsx", lang: "TypeScript", loc: 1273, code: 1090, comments: 95, blanks: 88, sizeBytes: 47071, complexity: 16.4 },
    { name: "Assets.tsx", path: "src/components/Assets.tsx", lang: "TypeScript", loc: 1180, code: 1020, comments: 80, blanks: 80, sizeBytes: 46128, complexity: 13.5 },
    { name: "Dashboard.tsx", path: "src/components/Dashboard.tsx", lang: "TypeScript", loc: 911, code: 790, comments: 65, blanks: 56, sizeBytes: 38434, complexity: 11.2 },
    { name: "Export.tsx", path: "src/components/Export.tsx", lang: "TypeScript", loc: 620, code: 540, comments: 42, blanks: 38, sizeBytes: 23613, complexity: 9.0 },
    { name: "Settings.tsx", path: "src/components/Settings.tsx", lang: "TypeScript", loc: 462, code: 390, comments: 36, blanks: 36, sizeBytes: 19500, complexity: 7.3 },
    { name: "Health.tsx", path: "src/components/Health.tsx", lang: "TypeScript", loc: 390, code: 330, comments: 32, blanks: 28, sizeBytes: 16063, complexity: 5.6 },
    { name: "Welcome.tsx", path: "src/components/Welcome.tsx", lang: "TypeScript", loc: 370, code: 310, comments: 30, blanks: 30, sizeBytes: 14363, complexity: 5.1 },
    { name: "Git.tsx", path: "src/components/Git.tsx", lang: "TypeScript", loc: 310, code: 260, comments: 26, blanks: 24, sizeBytes: 11425, complexity: 4.8 },
  ],
  duplicates: 0,
  duplicateGroups: [],
  averageComplexity: 3.4,
  complexityDist: [12, 10, 8, 5, 3, 2, 1, 1, 0, 0],
  edges: [
    ["src/App.tsx", "src/components/Dashboard.tsx"],
    ["src/App.tsx", "src/components/Health.tsx"],
    ["src/App.tsx", "src/components/Graph.tsx"],
    ["src/App.tsx", "src/components/Assets.tsx"],
    ["src/App.tsx", "src/components/Git.tsx"],
    ["src-tauri/src/engine/scanner.rs", "src-tauri/src/engine/complexity.rs"],
    ["src-tauri/src/engine/scanner.rs", "src-tauri/src/engine/architecture.rs"],
    ["src-tauri/src/engine/scanner.rs", "src-tauri/src/engine/techstack.rs"],
    ["src-tauri/src/engine/scanner.rs", "src-tauri/src/engine/assets.rs"],
  ],
  scanDurationMs: 142,
  uloc: 11890,
  dryness: 0.955,
  roleDistribution: {
    Core: { files: 22, loc: 9800, percentage: 61.4 },
    Infra: { files: 8, loc: 3100, percentage: 19.4 },
    Config: { files: 6, loc: 1650, percentage: 10.3 },
    Docs: { files: 4, loc: 950, percentage: 6.0 },
    Test: { files: 2, loc: 450, percentage: 2.8 },
  },
  annotations: [
    { kind: "TODO", filePath: "src/components/Welcome.tsx", lineNumber: 126, message: "Add folder drag and drop support" },
    { kind: "FIXME", filePath: "src/components/Insights.tsx", lineNumber: 260, message: "Normalize secret masks for multi-line blocks" },
  ],
  secrets: [],
  gitAvailable: true,
  fileChurn: [
    { filePath: "src-tauri/src/engine/scanner.rs", commits: 28 },
    { filePath: "src/components/Dashboard.tsx", commits: 22 },
    { filePath: "src/components/Graph.tsx", commits: 19 },
    { filePath: "src-tauri/src/engine/techstack.rs", commits: 16 },
    { filePath: "src/components/Assets.tsx", commits: 14 },
  ],
  topContributors: [
    { author: "ThanhNguyxn", commits: 64 },
  ],
  techStack: [
    { name: "Rust", version: "1.75+", category: "Language", icon: "code" },
    { name: "Tauri", version: "2.1.0", category: "Desktop Framework", icon: "desktop" },
    { name: "React", version: "19.1.0", category: "Frontend Framework", icon: "react" },
    { name: "Vite", version: "8.0.16", category: "Build Tool", icon: "vite" },
    { name: "Tailwind CSS", version: "4.3.0", category: "Styling", icon: "palette" },
    { name: "Recharts", version: "3.8.1", category: "Visualization", icon: "chart" },
  ],
  assetReport: {
    summary: {
      totalFiles: 2,
      totalSize: 1287116,
      categoryCounts: { multimedia: 2 },
      categorySizes: { multimedia: 1287116 },
      subcategoryCounts: { image: 2 },
    },
    assets: [
      { path: "assets/logo.png", name: "logo.png", extension: "png", size: 750528, category: "multimedia", subcategory: "image", description: "PNG Image" },
      { path: "assets/screenshot.png", name: "screenshot.png", extension: "png", size: 536588, category: "multimedia", subcategory: "image", description: "PNG Image" },
    ],
    duplicates: [],
    orphans: [],
    optimizationHints: [
      { path: "assets/logo.png", name: "logo.png", message: "Converting PNG to WebP can reduce file size by up to 70%", severity: "info", potentialSavings: 525000 },
    ],
    edges: [],
  },
};

export const mockCocomoResult: CocomoResult = {
  effortPersonMonths: 3.2,
  developmentTimeMonths: 2.8,
  estimatedCostUsd: 7680,
  teamSize: 1.1,
};
